meta_product_name: "Vivaio Millefoglie"
meta_title: "Millefoglie - Piante e Giardini"
meta_description: "Millefoglie è un giardino! Un vivaio a Ivrea (Piemonte) di piante erbacee perenni, graminacee
ornamentali e annuali da fiore, e un orto di fiori da taglio per bouquet e composizioni.
Acquista piante e fiori in vivaio e online, consegna fiori a domicilio, progettazione e realizzazione di
giardini e terrazzi."
meta_image: "site-preview2.jpg" # should exist in `app/assets/images/`
