meta_product_name: "Vivaio Millefoglie"
meta_title: "Millefoglie - Piante e Giardini"
meta_description: "Millefoglie è un vivaio a Ivrea con shop online dove acquistare piante selezionate con cura da esperti, consegna in tutta Italia. Fiori a domicilio a Ivrea e dintorni, progettazione di
giardini e terrazzi. Piante erbacee perenni, graminacee ornamentali e annuali da fiore, fiori da taglio per bouquet e composizioni.
"
meta_image: "site-preview2.jpg" # should exist in `app/assets/images/`
